version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - securetext-net

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - securetext-net

networks:
  securetext-net:
